# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dan Borthwickx
email: dan@smartcasual.cc
description: > # Dan Borthwick is a freelance Technology Consultant and Game Developer based in Melbourne, Australia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://smartcasual.cc" # the base hostname & protocol for your site
twitter_username: danborthwick
github_username:  danborthwick

# Build settings
markdown: kramdown
